EC/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
]

accounts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('signup/', views.SignupView.as_view(), name="signup"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView, name="logout"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!-- base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <title>EC</title>
    </head>
    <body>
    {% block header %}{% endblock %}
    {% block main %}{% endblock %}
    </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block main %}
<main class="form_main">
    <h1>EC(仮)</h1>
    <a href="{% url 'accounts:signup' %}" class="btn btn-primary">サインアップ</a>
    <a href="{% url 'accounts:login' %}" class="btn btn-primary">ログイン</a>
</main>
{% endblock %}